### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by yvesarrata** [sylvainPanneau/banger#13]
Let's have a way to log into the app ?

**Comment by nyc4m** [comment]
Yep make sense, but we also need a way to sign up ! we should use #10 supabase for that since it's going to handle login with social accounts and take care of securely store passwords

**Comment by yvesarrata** [comment]
### Enhancement

- [ ] animated background music related

**Comment by yvesarrata** [comment]
done didn't need password
maybe add an animated background in the future i dunno man perhaps

**Comment by nyc4m** [comment]
Yeah sure why not maybe
