### ISSUE TITLE
Implémenter le bouton retour dans le chat

### ISSUE THREAD

**Issue by nyc4m** [sylvainPanneau/banger#6]
Le bouton retour n'est actuellement pas implémenté, il faudrait que lors d'un click l'utilisateur soit ramené à l'écran précédent
![image](https://user-images.githubusercontent.com/16882406/151716273-609944a6-710c-4d19-8877-766fb6d5d922.png)

**Comment by yvesarrata** [comment]
ah bah c'est bon ça
